orbs:
  node: circleci/node@2.0.2

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - node/install:
          node-version: << parameters.version >>
          install-npm: true
      - run: npm run test

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              version: ["10", "11", "12", "13", "14"]
