orbs:
  node: circleci/node@2.0.2

version: 2.1
jobs:
  build:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - node/install:
          node-version: << parameters.version >>
          install-npm: true
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run test
          command: npm run test

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              version: ["10.22.0", "12.18.3", "14.9.0"]
