orbs:
  node: circleci/node@2.0.2

version: 2.1
jobs:
  build:
    parameters:
      docker-image:
        type: string
    docker:
      - image: << parameters.docker-image >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run test
          command: npm run test

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              docker-image: ["node:10", "node:12", "node:14"]
